/* Generated by AN DISI Unibo */ 
package it.unibo.timer_adapter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Timer_adapter extends QActorMsgQueue{
	public MsgHandle_Timer_adapter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
