/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.adapter_to_pfrs_mbot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Adapter_to_pfrs_mbot extends AbstractAdapter_to_pfrs_mbot { 
	public Adapter_to_pfrs_mbot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
