/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.time_ok;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Time_ok extends AbstractTime_ok { 
	public Time_ok(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
