/* Generated by AN DISI Unibo */ 
package it.unibo.ctxOutput;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Pfrs_event_driven extends AbstractPfrs_event_driven { 
	public Pfrs_event_driven(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
