/* Generated by AN DISI Unibo */ 
package it.unibo.input_element;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Input_element extends QActorMsgQueue{
	public MsgHandle_Input_element(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
