/* Generated by AN DISI Unibo */ 
package it.unibo.resource_model_time;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Resource_model_time extends QActorMsgQueue{
	public MsgHandle_Resource_model_time(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
