/* Generated by AN DISI Unibo */ 
package it.unibo.robot_movement_finder;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractRobot_movement_finder extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractRobot_movement_finder(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/robot_movement_finder/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/robot_movement_finder/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForModelChanged",waitForModelChanged);
	    	stateTab.put("applLogic",applLogic);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "robot_movement_finder tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"robot_movement_finder STARTED\"";
	    	println( temporaryStr );  
	    	//switchTo waitForModelChanged
	        switchToPlanAsNextState(pr, myselfName, "robot_movement_finder_"+myselfName, 
	              "waitForModelChanged",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForModelChanged = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForModelChanged",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForModelChanged";  
	    	//bbb
	     msgTransition( pr,myselfName,"robot_movement_finder_"+myselfName,false,
	          new StateFun[]{stateTab.get("applLogic") }, 
	          new String[]{"true","E","modelChanged" },
	          1000000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForModelChanged){  
	    	 println( getName() + " plan=waitForModelChanged WARNING:" + e_waitForModelChanged.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForModelChanged
	    
	    StateFun applLogic = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("applLogic",-1);
	    	String myselfName = "applLogic";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("modelChanged(resource(name(robot),state(movement(stopped),X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("modelChanged") && 
	    		pengine.unify(curT, Term.createTerm("modelChanged(resource(NAME,STATE))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="blinkOff";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("modelChanged(resource(NAME,STATE))"),  Term.createTerm("modelChanged(resource(name(robot),state(movement(stopped),X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "local_BlinkOff", parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("modelChanged(resource(name(robot),state(movement(movingForward),X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("modelChanged") && 
	    		pengine.unify(curT, Term.createTerm("modelChanged(resource(NAME,STATE))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="blinkOn";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("modelChanged(resource(NAME,STATE))"),  Term.createTerm("modelChanged(resource(name(robot),state(movement(movingForward),X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "local_BlinkOn", parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("modelChanged(resource(name(robot),state(movement(movingBackward),X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("modelChanged") && 
	    		pengine.unify(curT, Term.createTerm("modelChanged(resource(NAME,STATE))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="blinkOn";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("modelChanged(resource(NAME,STATE))"),  Term.createTerm("modelChanged(resource(name(robot),state(movement(movingBackward),X)))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "local_BlinkOn", parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("modelChanged(resource(name(robot),state(movement(movingForward),obstacleDetected(true))))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("modelChanged") && 
	    		pengine.unify(curT, Term.createTerm("modelChanged(resource(NAME,STATE))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="blinkOff";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("modelChanged(resource(NAME,STATE))"),  Term.createTerm("modelChanged(resource(name(robot),state(movement(movingForward),obstacleDetected(true))))"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "local_BlinkOff", parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"robot_movement_finder_"+myselfName,false,true);
	    }catch(Exception e_applLogic){  
	    	 println( getName() + " plan=applLogic WARNING:" + e_applLogic.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//applLogic
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
