/* Generated by AN DISI Unibo */ 
package it.unibo.robot_movement_finder;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robot_movement_finder extends QActorMsgQueue{
	public MsgHandle_Robot_movement_finder(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
