/* Generated by AN DISI Unibo */ 
package it.unibo.qa2frontend;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qa2frontend extends QActorMsgQueue{
	public MsgHandle_Qa2frontend(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
