/* Generated by AN DISI Unibo */ 
package it.unibo.frontend2qa;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Frontend2qa extends QActorMsgQueue{
	public MsgHandle_Frontend2qa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
