/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.frontend2qa;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Frontend2qa extends AbstractFrontend2qa { 
	public Frontend2qa(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
