/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.mock_output_time;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Mock_output_time extends AbstractMock_output_time { 
	public Mock_output_time(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
