/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.timer_adapter;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Timer_adapter extends AbstractTimer_adapter { 
	public Timer_adapter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
