/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.robot_movement_finder;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Robot_movement_finder extends AbstractRobot_movement_finder { 
	public Robot_movement_finder(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
