/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRealRobotAdapter;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evt_modelchanged extends AbstractEvt_modelchanged { 
	public Evt_modelchanged(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
