/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.collision_detector;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Collision_detector extends AbstractCollision_detector { 
	public Collision_detector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
