/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.handle_planner;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Handle_planner extends AbstractHandle_planner { 
	public Handle_planner(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
