/* Generated by AN DISI Unibo */ 
package it.unibo.robot_basic_movements;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robot_basic_movements extends QActorMsgQueue{
	public MsgHandle_Robot_basic_movements(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
