/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.robot_basic_movements;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Robot_basic_movements extends AbstractRobot_basic_movements { 
	public Robot_basic_movements(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
