/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.resource_model_time;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Resource_model_time extends AbstractResource_model_time { 
	public Resource_model_time(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
