/* Generated by AN DISI Unibo */ 
package it.unibo.adapter_to_pfrs_mbot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Adapter_to_pfrs_mbot extends QActorMsgQueue{
	public MsgHandle_Adapter_to_pfrs_mbot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
