/* Generated by AN DISI Unibo */ 
package it.unibo.mock_output_led;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mock_output_led extends QActorMsgQueue{
	public MsgHandle_Mock_output_led(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
