/* Generated by AN DISI Unibo */ 
package it.unibo.handle_planner;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Handle_planner extends QActorMsgQueue{
	public MsgHandle_Handle_planner(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
