/* Generated by AN DISI Unibo */ 
package it.unibo.temperature_sensor_adapter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Temperature_sensor_adapter extends QActorMsgQueue{
	public MsgHandle_Temperature_sensor_adapter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
