/* Generated by AN DISI Unibo */ 
package it.unibo.real_led;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractReal_led extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractReal_led(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/real_led/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/real_led/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForModelChanged",waitForModelChanged);
	    	stateTab.put("outputingData",outputingData);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "real_led tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"resource_representation_element STARTED\"";
	    	println( temporaryStr );  
	    	//switchTo waitForModelChanged
	        switchToPlanAsNextState(pr, myselfName, "real_led_"+myselfName, 
	              "waitForModelChanged",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForModelChanged = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForModelChanged",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForModelChanged";  
	    	//bbb
	     msgTransition( pr,myselfName,"real_led_"+myselfName,false,
	          new StateFun[]{stateTab.get("outputingData") }, 
	          new String[]{"true","E","modelChanged" },
	          1000000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForModelChanged){  
	    	 println( getName() + " plan=waitForModelChanged WARNING:" + e_waitForModelChanged.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForModelChanged
	    
	    StateFun outputingData = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("outputingData",-1);
	    	String myselfName = "outputingData";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?ledName(NAME)" )) != null ){
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("modelChanged(resource(name(NAME),state(on)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("modelChanged") && 
	    		pengine.unify(curT, Term.createTerm("modelChanged(resource(NAME,STATE))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			{/* JavaLikeMove */ 
	    			String arg1 = "./led28GpioTurnOn.sh" ;
	    			//end arg1
	    			it.unibo.myUtils.executor.execBash(this,arg1 );
	    			}
	    	}
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?ledName(NAME)" )) != null ){
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("modelChanged(resource(name(NAME),state(off)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("modelChanged") && 
	    		pengine.unify(curT, Term.createTerm("modelChanged(resource(NAME,STATE))")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			{/* JavaLikeMove */ 
	    			String arg1 = "./led28GpioTurnOff.sh" ;
	    			//end arg1
	    			it.unibo.myUtils.executor.execBash(this,arg1 );
	    			}
	    	}
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"real_led_"+myselfName,false,true);
	    }catch(Exception e_outputingData){  
	    	 println( getName() + " plan=outputingData WARNING:" + e_outputingData.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//outputingData
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
