/* Generated by AN DISI Unibo */ 
package it.unibo.stop_conditions_checker;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Stop_conditions_checker extends QActorMsgQueue{
	public MsgHandle_Stop_conditions_checker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
