/* Generated by AN DISI Unibo */ 
package it.unibo.sonar_checker;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sonar_checker extends QActorMsgQueue{
	public MsgHandle_Sonar_checker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
