/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.input_element;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Input_element extends AbstractInput_element { 
	public Input_element(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
