/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.resource_model_temperature;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Resource_model_temperature extends AbstractResource_model_temperature { 
	public Resource_model_temperature(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
