/* Generated by AN DISI Unibo */ 
package it.unibo.resource_model_robot;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractResource_model_robot extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractResource_model_robot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/resource_model_robot/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/resource_model_robot/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitMsgs",waitMsgs);
	    	stateTab.put("handleObstacle",handleObstacle);
	    	stateTab.put("handleRobot",handleRobot);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "resource_model_robot tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"resource_model_robot STARTS\"";
	    	println( temporaryStr );  
	    	parg = "consult(\"resourceModel.pl\")";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//switchTo waitMsgs
	        switchToPlanAsNextState(pr, myselfName, "resource_model_robot_"+myselfName, 
	              "waitMsgs",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitMsgs = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitMsgs",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitMsgs";  
	    	//bbb
	     msgTransition( pr,myselfName,"resource_model_robot_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleObstacle"), stateTab.get("handleRobot") }, 
	          new String[]{"true","M","msg_obstacleDetected", "true","M","msg_robotMovement" },
	          1000000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitMsgs){  
	    	 println( getName() + " plan=waitMsgs WARNING:" + e_waitMsgs.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitMsgs
	    
	    StateFun handleObstacle = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleObstacle",-1);
	    	String myselfName = "handleObstacle";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("obstacleDetected(VALUE)");
	    	if( currentMessage != null && currentMessage.msgId().equals("msg_obstacleDetected") && 
	    		pengine.unify(curT, Term.createTerm("obstacleDetected(VALUE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="changeModelItem(robot,obstacleDetected(VALUE))";
	    		/* PHead */
	    		parg =  updateVars( Term.createTerm("obstacleDetected(VALUE)"), 
	    		                    Term.createTerm("obstacleDetected(VALUE)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    			if( parg != null ) {
	    			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,86400000);
	    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "handleObstacle";
	    					if( aar.getTimeRemained() <= 0 ) addRule("tout(demo,"+getName()+")");
	    					if( ! aar.getGoon() ) return ;
	    				} 			
	    				if( aar.getResult().equals("failure")){
	    					if( ! aar.getGoon() ) return ;
	    				}else if( ! aar.getGoon() ) return ;
	    			}
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"resource_model_robot_"+myselfName,false,true);
	    }catch(Exception e_handleObstacle){  
	    	 println( getName() + " plan=handleObstacle WARNING:" + e_handleObstacle.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleObstacle
	    
	    StateFun handleRobot = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleRobot",-1);
	    	String myselfName = "handleRobot";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("robotMovement(VALUE)");
	    	if( currentMessage != null && currentMessage.msgId().equals("msg_robotMovement") && 
	    		pengine.unify(curT, Term.createTerm("robotMovement(VALUE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="changeModelItem(robot,movement(VALUE))";
	    		/* PHead */
	    		parg =  updateVars( Term.createTerm("robotMovement(VALUE)"), 
	    		                    Term.createTerm("robotMovement(VALUE)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    			if( parg != null ) {
	    			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,86400000);
	    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "handleRobot";
	    					if( aar.getTimeRemained() <= 0 ) addRule("tout(demo,"+getName()+")");
	    					if( ! aar.getGoon() ) return ;
	    				} 			
	    				if( aar.getResult().equals("failure")){
	    					if( ! aar.getGoon() ) return ;
	    				}else if( ! aar.getGoon() ) return ;
	    			}
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"resource_model_robot_"+myselfName,false,true);
	    }catch(Exception e_handleRobot){  
	    	 println( getName() + " plan=handleRobot WARNING:" + e_handleRobot.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleRobot
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
