/* Generated by AN DISI Unibo */ 
package it.unibo.resource_model_robot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Resource_model_robot extends QActorMsgQueue{
	public MsgHandle_Resource_model_robot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
