/* Generated by AN DISI Unibo */ 
package it.unibo.ctxResourceModel;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evt_robot extends AbstractEvt_robot { 
	public Evt_robot(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
