/* Generated by AN DISI Unibo */ 
package it.unibo.ctxResourceModel;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Logger extends AbstractLogger { 
	public Logger(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
