/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.initial_conditions_checker;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Initial_conditions_checker extends AbstractInitial_conditions_checker { 
	public Initial_conditions_checker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
