/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.temperature_sensor_adapter;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Temperature_sensor_adapter extends AbstractTemperature_sensor_adapter { 
	public Temperature_sensor_adapter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
