/* Generated by AN DISI Unibo */ 
package it.unibo.initial_conditions_checker;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Initial_conditions_checker extends QActorMsgQueue{
	public MsgHandle_Initial_conditions_checker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
