/* Generated by AN DISI Unibo */ 
package it.unibo.resource_model_temperature;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Resource_model_temperature extends QActorMsgQueue{
	public MsgHandle_Resource_model_temperature(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
