/* Generated by AN DISI Unibo */ 
package it.unibo.collision_detector;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Collision_detector extends QActorMsgQueue{
	public MsgHandle_Collision_detector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
