/* Generated by AN DISI Unibo */ 
package it.unibo.real_led;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Real_led extends QActorMsgQueue{
	public MsgHandle_Real_led(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
